### ISSUE TITLE
Option to copy id to clipboard 

### ISSUE THREAD

**Issue by planemad** [aarthykc/changesetID#1]
@aarthykc The plugin option to show the alert is redundant. The user can just disable the plugin from the list for that.

<img width="245" alt="screenshot 2016-01-25 11 38 29" src="https://cloud.githubusercontent.com/assets/126868/12543709/440d9746-c358-11e5-8596-8981cb6be415.png">

What would be actually useful is an option to automatically copy the changeset id to the clipboard:
- [ ] Copy id to the clipboard

**Comment by aarthykc** [comment]
Done https://github.com/aarthykc/changesetID/releases/tag/v1.2
