### ISSUE TITLE
Error message shows up after downloading the OSM data

### ISSUE THREAD

**Issue by jothirnadh** [aarthykc/changesetID#7]
While trying to download the data in JOSM the below message shows up everytime. The error message don't have any of the plugin information, so it took me time understand which plugin is causing this error. This issue is encountered since the last two versions (version 10161 & 10526). @aarthykc can you please look into this?

![screen shot 2016-07-26 at 6 44 44 pm](https://cloud.githubusercontent.com/assets/8401827/17139326/95203bc2-5361-11e6-8882-213a050db757.png)

**Comment by aarthykc** [comment]
@jothirnadh, @planemad, dunzo -- https://github.com/aarthykc/changesetID/releases/tag/2.0
